name: Generate Rewrite Proposal with Mistral

on:
  issues:
    types: [labeled]

jobs:
  call:
    if: github.event.label.name == 'needs-mistral'
    uses: ./.github/workflows/reusable-mistral-generator.yml
    secrets:
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
