name: PO - Handle Clarification OK Label

on:
  issues:
    types: [labeled]

jobs:
  call:
    if: github.event.label.name == 'clarification-ok' && contains(github.event.issue.labels.*.name, 'clarification-ok')
    uses: ./.github/workflows/reusable-po-clarified.yml
    secrets:
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
