name: PO - Create Required Labels

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/*.yml'

jobs:
  call:
    uses: ./.github/workflows/reusable-po-labels.yml
